<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsTrimmable>false</IsTrimmable>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BlazorWindowManager\BlazorWindowManager\BlazorWindowManager.csproj" />
    <ProjectReference Include="..\..\BlazorTerminal\src\BlazorTerminal\BlazorTerminal.csproj" />
  </ItemGroup>

</Project>
